blank_issues_enabled: false
contact_links:
  - name: 💬 General Discussion
    url: https://github.com/afifashamsadvivo/zen-captcha-core/discussions
    about: For when you just want to talk about neon lights and robots.
